### ISSUE TITLE
Bad idea

### ISSUE THREAD

**Issue by yamashi** [iAmThatMichael/CyberpunkPatches#1]
It would be much better to make a PR to improve what can be improved instead of copy pasting the work to create the same thing and doing it wrong (mutex spin and debug menu for example).

Edit: you also cannot relicense my code...

**Comment by iAmThatMichael** [comment]
Removed offending code and removed reference. Current implementation is currently fine, if there's an issue let me know.

**Comment by yamashi** [comment]
You still need to attribute the research you have taken. 
This is just bad etiquette.

Do your own research.
